### ISSUE TITLE
Add priority on requestRoutingRules

### ISSUE THREAD

**Issue by jawad846** [aztfm/terraform-azurerm-application-gateway#10]
All request routing rules should have a priority defined starting from api-version 2021-08-01

**Comment by jawad846** [comment]
Getting below error;


creating Application Gateway: (Name "amf-ph-dr-prod-uaen-api-appgw" / Resource Group "amf-ph-dr-prod-uaen-hub-rg"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayRequestRoutingRulePriorityCannotBeEmpty" Message="Priority for the request routing rule /subscriptions/0ebd5e01-aefe-46ab-b87f-db35dc53edfe/resourceGroups/amf-ph-dr-prod-uaen-hub-rg/providers/Microsoft.Network/applicationGateways/amf-ph-dr-prod-uaen-api-appgw/requestRoutingRules/amf-ph-dr-prod-uaen-appgw-default-routingrule cannot be empty. All request routing rules should have a priority defined starting from api-version 2021-08-01" Details=[]



Edited -->

```
  dynamic "request_routing_rule" {
    for_each = var.request_routing_rules
    content {
      name                        = request_routing_rule.value.name
      priority                    = request_routing_rule.value.priority
      rule_type                   = lookup(request_routing_rule.value, "rule_type", "Basic")
      http_listener_name          = request_routing_rule.value.http_listener_name
      backend_address_pool_name   = request_routing_rule.value.redirect_configuration_name == null ? request_routing_rule.value.backend_address_pool_name : null
      backend_http_settings_name  = request_routing_rule.value.redirect_configuration_name == null ? request_routing_rule.value.backend_http_settings_name : null
      redirect_configuration_name = lookup(request_routing_rule.value, "redirect_configuration_name", null)
      rewrite_rule_set_name       = lookup(request_routing_rule.value, "rewrite_rule_set_name", null)
      url_path_map_name           = lookup(request_routing_rule.value, "url_path_map_name", null)
    }
  }
```

**Comment by gareda** [comment]
@jawad846 feature added in version 2.0.0
